project_id = "wxwoazvqmdvgghdqzdln"

[functions.chat-with-agent]
verify_jwt = false

[functions.generate-metabase-token]
verify_jwt = false

[functions.slack-agent-events]
verify_jwt = false

[functions.google-chat-agent-events]
verify_jwt = false
