import { memo, useMemo, lazy, Suspense } from "react";
import { ScrollArea } from "@/components/ui/scroll-area";
import { type ChartSpec } from "@/components/chat/MarkdownChartLazy";
import type { ChatMessage } from "@/hooks/useChat";

const MarkdownChartLazy = lazy(() =>
  import("@/components/chat/MarkdownChartLazy").then((m) => ({ default: m.MarkdownChart }))
);

interface GalleryItem {
  messageId: string;
  created_at: string;
  type: "chart" | "table";
  chartSpec?: ChartSpec;
  tableMarkdown?: string;
}

const CHART_BLOCK_RE = /```chart\s*\n([\s\S]*?)\n```/g;
const TABLE_RE = /(?:^|\n)(\|.+\|(?:\n\|[-: |]+\|)(?:\n\|.+\|)+)/g;

const isChartSpec = (value: unknown): value is ChartSpec => {
  if (!value || typeof value !== "object") return false;
  const c = value as Partial<ChartSpec>;
  if (c.type === "bar" || c.type === "line")
    return Boolean(c.title && c.xKey && Array.isArray((c as any).series) && Array.isArray(c.data));
  if (c.type === "pie")
    return Boolean(c.title && (c as any).labelKey && (c as any).valueKey && Array.isArray(c.data));
  return false;
};

function extractGalleryItems(messages: ChatMessage[]): GalleryItem[] {
  const items: GalleryItem[] = [];

  for (const msg of messages) {
    if (msg.role !== "assistant") continue;

    const normalizedContent = msg.content
      .replace(/\\r\\n/g, "\n")
      .replace(/\\n/g, "\n")
      .replace(/\\t/g, "\t")
      .replace(/\r\n/g, "\n")
      .trimEnd();

    // Extract charts
    let match: RegExpExecArray | null;
    CHART_BLOCK_RE.lastIndex = 0;
    while ((match = CHART_BLOCK_RE.exec(normalizedContent)) !== null) {
      try {
        const parsed = JSON.parse(match[1]);
        if (isChartSpec(parsed)) {
          items.push({
            messageId: msg.id,
            created_at: msg.created_at,
            type: "chart",
            chartSpec: parsed,
          });
        }
      } catch {
        // skip malformed
      }
    }

    // Extract tables
    TABLE_RE.lastIndex = 0;
    while ((match = TABLE_RE.exec(normalizedContent)) !== null) {
      items.push({
        messageId: msg.id,
        created_at: msg.created_at,
        type: "table",
        tableMarkdown: match[1].trim(),
      });
    }
  }

  // Chronological order (newest first)
  return items.sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());
}

const TablePreview = memo(({ markdown }: { markdown: string }) => {
  const lines = markdown.split("\n").filter(Boolean);
  const headerCells = lines[0]?.split("|").filter((c) => c.trim()).map((c) => c.trim()) || [];
  const dataRows = lines.slice(2).map((line) => line.split("|").filter((c) => c.trim()).map((c) => c.trim()));
  // Show only first 5 rows in preview
  const previewRows = dataRows.slice(0, 5);

  return (
    <div className="w-full overflow-x-auto rounded-lg border border-border/60">
      <table className="w-full text-xs">
        <thead>
          <tr className="border-b border-border/40">
            {headerCells.map((cell, i) => (
              <th key={i} className="px-2 py-1.5 text-left font-semibold text-foreground">{cell}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {previewRows.map((row, ri) => (
            <tr key={ri} className="border-b border-border/20 last:border-0">
              {row.map((cell, ci) => (
                <td key={ci} className="px-2 py-1 text-muted-foreground">{cell}</td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
      {dataRows.length > 5 && (
        <div className="px-2 py-1 text-[0.625rem] text-muted-foreground/60">+{dataRows.length - 5} more rows</div>
      )}
    </div>
  );
});

function formatDate(dateStr: string) {
  const d = new Date(dateStr);
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" });
}

interface ChatGalleryProps {
  messages: ChatMessage[];
}

const ChatGallery = memo(({ messages }: ChatGalleryProps) => {
  const items = useMemo(() => extractGalleryItems(messages), [messages]);

  if (items.length === 0) {
    return (
      <div className="flex flex-1 items-center justify-center px-4 text-center">
        <div className="space-y-2">
          <p className="text-sm text-muted-foreground">No charts or tables yet.</p>
          <p className="text-xs text-muted-foreground/60">Charts and tables generated by the AI will appear here.</p>
        </div>
      </div>
    );
  }

  return (
    <ScrollArea className="flex-1">
      <div className="space-y-4 px-2 py-3">
        {items.map((item, idx) => (
          <div key={`${item.messageId}-${idx}`} className="space-y-1.5">
            <p className="label-tech px-1">{formatDate(item.created_at)}</p>
            {item.type === "chart" && item.chartSpec && (
              <Suspense fallback={<div className="flex h-32 items-center justify-center rounded-xl border border-border/40 text-xs text-muted-foreground">Loading chart...</div>}>
                <MarkdownChartLazy spec={item.chartSpec} />
              </Suspense>
            )}
            {item.type === "table" && item.tableMarkdown && (
              <TablePreview markdown={item.tableMarkdown} />
            )}
          </div>
        ))}
      </div>
    </ScrollArea>
  );
});

export default ChatGallery;
