INSERT INTO public.agent_sql_runs (id,message_id,executed_sql,bq_result,created_at) VALUES
('b7d66d62-7b09-49b6-aed1-1cd7b3a24123','6331bf42-f0f7-4468-89a6-e0c965810f04','SELECT branch, COUNT(DISTINCT contact) AS registrations FROM `tenms-userdb.Marketing_Leads.offline_leads_api` GROUP BY branch ORDER BY branch;SELECT branch, COUNT(DISTINCT contact) AS registrations FROM `tenms-userdb.Marketing_Leads.offline_leads_api` GROUP BY branch ORDER BY branch
;','[{"schema":{"fields":[{"name":"branch","type":"STRING","mode":"NULLABLE"},{"name":"registrations","type":"INTEGER","mode":"NULLABLE"}]},"rows":[{"f":[{"v":null},{"v":"11571"}]},{"f":[{"v":"\u003ctest lead: dummy data for আপনি কোন প্রোগ্রামের জন্য ফ্রি ক্লাসে জয়েন করতে চান?\u003e"},{"v":"0"}]},{"f":[{"v":"\u003ctest lead: dummy data for কোন Branch এ ক্লাস করতে চাও ?\u003e"},{"v":"0"}]},{"f":[{"v":"Chawkbazar Branch"},{"v":"39309"}]},{"f":[{"v":"Mirpur Branch"},{"v":"66903"}]},{"f":[{"v":"Moghbazar Branch"},{"v":"29238"}]},{"f":[{"v":"Panthapath Branch"},{"v":"39029"}]},{"f":[{"v":"Uttara Branch"},{"v":"89097"}]}],"jobComplete":true}], [{"schema":{"fields":[{"name":"branch","type":"STRING","mode":"NULLABLE"},{"name":"registrations","type":"INTEGER","mode":"NULLABLE"}]},"rows":[{"f":[{"v":null},{"v":"11571"}]},{"f":[{"v":"\u003ctest lead: dummy data for আপনি কোন প্রোগ্রামের জন্য ফ্রি ক্লাসে জয়েন করতে চান?\u003e"},{"v":"0"}]},{"f":[{"v":"\u003ctest lead: dummy data for কোন Branch এ ক্লাস করতে চাও ?\u003e"},{"v":"0"}]},{"f":[{"v":"Chawkbazar Branch"},{"v":"39309"}]},{"f":[{"v":"Mirpur Branch"},{"v":"66903"}]},{"f":[{"v":"Moghbazar Branch"},{"v":"29238"}]},{"f":[{"v":"Panthapath Branch"},{"v":"39029"}]},{"f":[{"v":"Uttara Branch"},{"v":"89097"}]}],"jobComplete":true}
], []','2026-03-21 21:26:56.337241+00'),
('1a4a0876-9b74-469a-bc6a-2b24dd6e53a8','0c894958-2a89-4e6e-807c-38d25c498146','SELECT branch, COUNT(DISTINCT contact) AS registrations FROM `tenms-userdb.Marketing_Leads.offline_leads_api` GROUP BY branch ORDER BY branch;SELECT branch, COUNT(DISTINCT Mobile_Number) AS admissions FROM `tenms-userdb.english_centre.offline_admissions_gsheet_v3` GROUP BY branch ORDER BY branch
;','[{"schema":{"fields":[{"name":"branch","type":"STRING","mode":"NULLABLE"},{"name":"admissions","type":"INTEGER","mode":"NULLABLE"}]},"rows":[{"f":[{"v":"Chawkbazar Branch"},{"v":"1287"}]},{"f":[{"v":"Mirpur Branch"},{"v":"2729"}]},{"f":[{"v":"Moghbazar Branch"},{"v":"2638"}]},{"f":[{"v":"Panthapath Branch"},{"v":"3401"}]},{"f":[{"v":"Uttara Branch"},{"v":"3413"}]}],"jobComplete":true}], [{"schema":{"fields":[{"name":"branch","type":"STRING","mode":"NULLABLE"},{"name":"admissions","type":"INTEGER","mode":"NULLABLE"}]},"rows":[{"f":[{"v":"Chawkbazar Branch"},{"v":"1287"}]},{"f":[{"v":"Mirpur Branch"},{"v":"2729"}]},{"f":[{"v":"Moghbazar Branch"},{"v":"2638"}]},{"f":[{"v":"Panthapath Branch"},{"v":"3401"}]},{"f":[{"v":"Uttara Branch"},{"v":"3413"}]}],"jobComplete":true}
], []','2026-03-21 21:43:40.27103+00'),
('be653b63-f7f8-49e8-b505-92dcba68c614','22b1a6e1-930c-4d1a-af60-6cc631a3375c','SELECT branch, COUNT(DISTINCT contact) AS registrations FROM `tenms-userdb.Marketing_Leads.offline_leads_api` GROUP BY branch ORDER BY branch;SELECT branch, COUNT(DISTINCT Mobile_Number) AS admissions FROM `tenms-userdb.english_centre.offline_admissions_gsheet_v3` GROUP BY branch ORDER BY branch
;
','[{"schema":{"fields":[{"name":"branch","type":"STRING","mode":"NULLABLE"},{"name":"registrations","type":"INTEGER","mode":"NULLABLE"}]},"rows":[{"f":[{"v":null},{"v":"11571"}]},{"f":[{"v":"\u003ctest lead: dummy data for আপনি কোন প্রোগ্রামের জন্য ফ্রি ক্লাসে জয়েন করতে চান?\u003e"},{"v":"0"}]},{"f":[{"v":"\u003ctest lead: dummy data for কোন Branch এ ক্লাস করতে চাও ?\u003e"},{"v":"0"}]},{"f":[{"v":"Chawkbazar Branch"},{"v":"39309"}]},{"f":[{"v":"Mirpur Branch"},{"v":"66903"}]},{"f":[{"v":"Moghbazar Branch"},{"v":"29238"}]},{"f":[{"v":"Panthapath Branch"},{"v":"39029"}]},{"f":[{"v":"Uttara Branch"},{"v":"89097"}]}],"jobComplete":true}
], [{"schema":{"fields":[{"name":"branch","type":"STRING","mode":"NULLABLE"},{"name":"admissions","type":"INTEGER","mode":"NULLABLE"}]},"rows":[{"f":[{"v":"Chawkbazar Branch"},{"v":"1287"}]},{"f":[{"v":"Mirpur Branch"},{"v":"2729"}]},{"f":[{"v":"Moghbazar Branch"},{"v":"2638"}]},{"f":[{"v":"Panthapath Branch"},{"v":"3401"}]},{"f":[{"v":"Uttara Branch"},{"v":"3413"}]}],"jobComplete":true}
], [
]','2026-03-21 21:45:15.440472+00'),
('72a19e8b-1942-45d7-8929-9e07bb67d7f1','c36f8c07-d15d-4824-b0a7-ea0a5e205f9a','SELECT ROUND(SAFE_DIVIDE(COUNT(DISTINCT CASE WHEN attendance_status IN (''present'',''present_early'',''present_late'') THEN contact END), COUNT(DISTINCT contact)) * 100, 2) AS rta_percentage FROM `tenms-userdb.Marketing_Leads.offline_leads_api` WHERE submission_date BETWEEN DATE ''2026-02-01'' AND DATE ''2026-02-28'';
;
','[{"schema":{"fields":[{"name":"rta_percentage","type":"FLOAT","mode":"NULLABLE"}]},"rows":[{"f":[{"v":"11.08"}]}],"jobComplete":true}
], [
], [
]','2026-03-21 21:45:53.558722+00'),
('9eb775c6-6c09-4fb7-92b9-9435f9516f4d','c45cddfc-2a4b-452b-9d79-597c4441fd03','SELECT branch, COUNT(DISTINCT contact) AS registrations FROM `tenms-userdb.Marketing_Leads.offline_leads_api` GROUP BY branch ORDER BY branch;SELECT branch, COUNT(DISTINCT Mobile_Number) AS admissions FROM `tenms-userdb.english_centre.offline_admissions_gsheet_v3` GROUP BY branch ORDER BY branch
;
','[{"schema":{"fields":[{"name":"branch","type":"STRING","mode":"NULLABLE"},{"name":"registrations","type":"INTEGER","mode":"NULLABLE"}]},"rows":[{"f":[{"v":null},{"v":"11517"}]},{"f":[{"v":"\u003ctest lead: dummy data for আপনি কোন প্রোগ্রামের জন্য ফ্রি ক্লাসে জয়েন করতে চান?\u003e"},{"v":"0"}]},{"f":[{"v":"\u003ctest lead: dummy data for কোন Branch এ ক্লাস করতে চাও ?\u003e"},{"v":"0"}]},{"f":[{"v":"Chawkbazar Branch"},{"v":"39331"}]},{"f":[{"v":"Mirpur Branch"},{"v":"66935"}]},{"f":[{"v":"Moghbazar Branch"},{"v":"29252"}]},{"f":[{"v":"Panthapath Branch"},{"v":"39051"}]},{"f":[{"v":"Uttara Branch"},{"v":"89141"}]}],"jobComplete":true}
], [{"schema":{"fields":[{"name":"branch","type":"STRING","mode":"NULLABLE"},{"name":"admissions","type":"INTEGER","mode":"NULLABLE"}]},"rows":[{"f":[{"v":"Chawkbazar Branch"},{"v":"1287"}]},{"f":[{"v":"Mirpur Branch"},{"v":"2729"}]},{"f":[{"v":"Moghbazar Branch"},{"v":"2638"}]},{"f":[{"v":"Panthapath Branch"},{"v":"3401"}]},{"f":[{"v":"Uttara Branch"},{"v":"3413"}]}],"jobComplete":true}
], [
]','2026-03-22 04:25:39.062652+00')
ON CONFLICT (id) DO NOTHING;