INSERT INTO public.agent_sql_runs (id,message_id,executed_sql,bq_result,created_at) VALUES
('5bd4eb9b-c53f-4a53-91ce-7ae6ca08dff7','8747b987-1001-4e32-a8a8-d81d14bfd065','SELECT COUNT(DISTINCT mobile_number) AS walkin_count FROM `tenms-userdb.ab_ihelp_report_db.visitor_ledger_view` WHERE visit_type = ''Walk-in'' AND visiting_date = CURRENT_DATE() - 1 LIMIT 1000;SELECT COUNT(DISTINCT contact) AS free_class_count FROM `tenms-userdb.Marketing_Leads.offline_leads_api` WHERE submission_date = CURRENT_DATE() - 1 LIMIT 1000
;{"schema":{"fields":[{"name":"admission_count","type":"INTEGER","mode":"NULLABLE"}]},"rows":[{"f":[{"v":"15"}]}],"jobComplete":true}
','[{"schema":{"fields":[{"name":"walkin_count","type":"INTEGER","mode":"NULLABLE"}]},"rows":[{"f":[{"v":"12"}]}],"jobComplete":true}
], [{"schema":{"fields":[{"name":"free_class_count","type":"INTEGER","mode":"NULLABLE"}]},"rows":[{"f":[{"v":"378"}]}],"jobComplete":true}
], [{"schema":{"fields":[{"name":"admission_count","type":"INTEGER","mode":"NULLABLE"}]},"rows":[{"f":[{"v":"15"}]}],"jobComplete":true}
]','2026-03-31 06:54:26.612473+00'),
('8cc91f94-849c-49a8-a0a3-98ad0364c990','68c7d812-29cc-450e-8989-e854bf307061','SELECT data_source AS booking_source, COUNT(DISTINCT contact) AS free_class_registrations, COUNT(DISTINCT CASE WHEN attendance_status IN (''present'',''present_early'',''present_late'') THEN contact END) AS attendance_count FROM `tenms-userdb.Marketing_Leads.offline_leads_api` WHERE submission_date = CURRENT_DATE() - 1 GROUP BY data_source ORDER BY free_class_registrations DESC LIMIT 1000;
;
','[{"schema":{"fields":[{"name":"booking_source","type":"STRING","mode":"NULLABLE"},{"name":"free_class_registrations","type":"INTEGER","mode":"NULLABLE"},{"name":"attendance_count","type":"INTEGER","mode":"NULLABLE"}]},"rows":[{"f":[{"v":"Facebook Form"},{"v":"271"},{"v":"0"}]},{"f":[{"v":"Booking System"},{"v":"90"},{"v":"0"}]},{"f":[{"v":"ClassroomOS"},{"v":"22"},{"v":"16"}]},{"f":[{"v":"iHelp"},{"v":"1"},{"v":"0"}]}],"jobComplete":true}
], [
], [
]','2026-03-31 06:55:31.939804+00'),
('db2303d7-9532-4027-9d27-d5ab7e29c8d7','b7668775-a1ec-49d0-8cbf-8eb12633323c','SELECT Employee_Name, Designation, branch, Month, Working_Days, Present, Absent, Leave, Late, attendance_pct, visitors, admissions, ado_cvr, team_collaboration_score, service_rating_score, employee_score, employee_final_score, status FROM `tenms-userdb.english_centre.ec_ado_fdo_perf_cal` WHERE Designation = ''ADO'' ORDER BY employee_final_score ASC, admissions ASC, visitors ASC LIMIT 1000;SELECT Email_Address AS ado_email, branch, COUNT(DISTINCT Mobile_Number) AS admissions, SUM(SAFE_CAST(Actual_Revenue AS FLOAT64)) AS booking_revenue, SUM(SAFE_CAST(Amount_Collected AS FLOAT64)) AS collected_amount, SUM(SAFE_CAST(Amount_Due AS FLOAT64)) AS due_amount FROM `tenms-userdb.english_centre.offline_admissions_gsheet_v3` WHERE admission_date BETWEEN DATE_TRUNC(CURRENT_DATE(), MONTH) AND CURRENT_DATE() GROUP BY ado_email, branch ORDER BY admissions ASC, collected_amount ASC LIMIT 1000
;{"schema":{"fields":[{"name":"ado_email","type":"STRING","mode":"NULLABLE"},{"name":"branch","type":"STRING","mode":"NULLABLE"},{"name":"walkins","type":"INTEGER","mode":"NULLABLE"},{"name":"walkin_admissions","type":"INTEGER","mode":"NULLABLE"},{"name":"free_class_visitors","type":"INTEGER","mode":"NULLABLE"}]},"rows":[{"f":[{"v":"shatabdi@10minuteschool.com"},{"v":"Panthapath Branch"},{"v":"0"},{"v":"0"},{"v":"1"}]},{"f":[{"v":"touhidul.maruf@10minuteschool.com"},{"v":"Uttara Branch"},{"v":"4"},{"v":"0"},{"v":"8"}]},{"f":[{"v":"farjana.eva@10minuteschool.com"},{"v":"Chawkbazar Branch"},{"v":"15"},{"v":"0"},{"v":"24"}]},{"f":[{"v":"farjana@10minuteschool.com"},{"v":"Mirpur Branch"},{"v":"1"},{"v":"1"},{"v":"1"}]},{"f":[{"v":"jogodish@10minuteschool.com"},{"v":"Mirpur Branch"},{"v":"2"},{"v":"1"},{"v":"38"}]},{"f":[{"v":"shatabdi@10minuteschool.com"},{"v":"Mirpur Branch"},{"v":"7"},{"v":"1"},{"v":"42"}]},{"f":[{"v":"rodela@10minuteschool.com"},{"v":"Moghbazar Branch"},{"v":"2"},{"v":"2"},{"v":"2"}]},{"f":[{"v":"puspo@10minuteschool.com"},{"v":"Chawkbazar Branch"},{"v":"23"},{"v":"2"},{"v":"25"}]},{"f":[{"v":"hayatun@10minuteschool.com"},{"v":"Moghbazar Branch"},{"v":"4"},{"v":"3"},{"v":"4"}]},{"f":[{"v":"protyasha@10minuteschool.com"},{"v":"Moghbazar Branch"},{"v":"19"},{"v":"4"},{"v":"9"}]},{"f":[{"v":"raheta@10minuteschool.com"},{"v":"Chawkbazar Branch"},{"v":"23"},{"v":"5"},{"v":"38"}]},{"f":[{"v":"fahim@10minuteschool.com"},{"v":"Mirpur Branch"},{"v":"7"},{"v":"5"},{"v":"40"}]},{"f":[{"v":"eva@10minuteschool.com"},{"v":"Uttara Branch"},{"v":"12"},{"v":"6"},{"v":"8"}]},{"f":[{"v":"meem@10minuteschool.com"},{"v":"Panthapath Branch"},{"v":"16"},{"v":"8"},{"v":"12"}]},{"f":[{"v":"mim@10minuteschool.com"},{"v":"Uttara Branch"},{"v":"11"},{"v":"9"},{"v":"10"}]},{"f":[{"v":"lamim@10minuteschool.com"},{"v":"Moghbazar Branch"},{"v":"10"},{"v":"10"},{"v":"5"}]},{"f":[{"v":"al.amin@10minuteschool.com"},{"v":"Panthapath Branch"},{"v":"16"},{"v":"11"},{"v":"11"}]},{"f":[{"v":"alpana@10minuteschool.com"},{"v":"Uttara Branch"},{"v":"17"},{"v":"12"},{"v":"12"}]},{"f":[{"v":"sornali@10minuteschool.com"},{"v":"Panthapath Branch"},{"v":"26"},{"v":"16"},{"v":"39"}]}],"jobComplete":true}
','[{"schema":{"fields":[{"name":"Employee_Name","type":"STRING","mode":"NULLABLE"},{"name":"Designation","type":"STRING","mode":"NULLABLE"},{"name":"branch","type":"STRING","mode":"NULLABLE"},{"name":"Month","type":"STRING","mode":"NULLABLE"},{"name":"Working_Days","type":"STRING","mode":"NULLABLE"},{"name":"Present","type":"STRING","mode":"NULLABLE"},{"name":"Absent","type":"STRING","mode":"NULLABLE"},{"name":"Leave","type":"STRING","mode":"NULLABLE"},{"name":"Late","type":"STRING","mode":"NULLABLE"},{"name":"attendance_pct","type":"FLOAT","mode":"NULLABLE"},{"name":"visitors","type":"INTEGER","mode":"NULLABLE"},{"name":"admissions","type":"INTEGER","mode":"NULLABLE"},{"name":"ado_cvr","type":"FLOAT","mode":"NULLABLE"},{"name":"team_collaboration_score","type":"FLOAT","mode":"NULLABLE"},{"name":"service_rating_score","type":"FLOAT","mode":"NULLABLE"},{"name":"employee_score","type":"FLOAT","mode":"NULLABLE"},{"name":"employee_final_score","type":"FLOAT","mode":"NULLABLE"},{"name":"status","type":"STRING","mode":"NULLABLE"}]},"jobComplete":true}
], [{"schema":{"fields":[{"name":"ado_email","type":"STRING","mode":"NULLABLE"},{"name":"branch","type":"STRING","mode":"NULLABLE"},{"name":"admissions","type":"INTEGER","mode":"NULLABLE"},{"name":"booking_revenue","type":"FLOAT","mode":"NULLABLE"},{"name":"collected_amount","type":"FLOAT","mode":"NULLABLE"},{"name":"due_amount","type":"FLOAT","mode":"NULLABLE"}]},"rows":[{"f":[{"v":"farjana@10minuteschool.com"},{"v":"Mirpur Branch"},{"v":"3"},{"v":"75000.0"},{"v":"36500.0"},{"v":"38500.0"}]},{"f":[{"v":"farjana.eva@10minuteschool.com"},{"v":"Chawkbazar Branch"},{"v":"4"},{"v":"62200.0"},{"v":"37500.0"},{"v":"24700.0"}]},{"f":[{"v":"puspo@10minuteschool.com"},{"v":"Chawkbazar Branch"},{"v":"5"},{"v":"45400.0"},{"v":"22700.0"},{"v":"22700.0"}]},{"f":[{"v":"shatabdi@10minuteschool.com"},{"v":"Mirpur Branch"},{"v":"8"},{"v":"119700.0"},{"v":"61000.0"},{"v":"58700.0"}]},{"f":[{"v":"raheta@10minuteschool.com"},{"v":"Chawkbazar Branch"},{"v":"8"},{"v":"91200.0"},{"v":"66000.0"},{"v":"25200.0"}]},{"f":[{"v":"jogodish@10minuteschool.com"},{"v":"Mirpur Branch"},{"v":"9"},{"v":"137500.0"},{"v":"50000.0"},{"v":"87500.0"}]},{"f":[{"v":"protyasha@10minuteschool.com"},{"v":"Moghbazar Branch"},{"v":"9"},{"v":"126500.0"},{"v":"115000.0"},{"v":"11500.0"}]},{"f":[{"v":"eva@10minuteschool.com"},{"v":"Uttara Branch"},{"v":"10"},{"v":"218000.0"},{"v":"51500.0"},{"v":"166500.0"}]},{"f":[{"v":"hayatun@10minuteschool.com"},{"v":"Moghbazar Branch"},{"v":"10"},{"v":"115000.0"},{"v":"89520.0"},{"v":"25480.0"}]},{"f":[{"v":"rodela@10minuteschool.com"},{"v":"Moghbazar Branch"},{"v":"11"},{"v":"154000.0"},{"v":"100000.0"},{"v":"54000.0"}]},{"f":[{"v":"fahim@10minuteschool.com"},{"v":"Mirpur Branch"},{"v":"11"},{"v":"168500.0"},{"v":"140000.0"},{"v":"28500.0"}]},{"f":[{"v":"alpana@10minuteschool.com"},{"v":"Uttara Branch"},{"v":"20"},{"v":"277400.0"},{"v":"104100.0"},{"v":"191800.0"}]},{"f":[{"v":"mim@10minuteschool.com"},{"v":"Uttara Branch"},{"v":"21"},{"v":"309000.0"},{"v":"222140.0"},{"v":"102960.0"}]},{"f":[{"v":"al.amin@10minuteschool.com"},{"v":"Panthapath Branch"},{"v":"21"},{"v":"252500.0"},{"v":"251000.0"},{"v":"8500.0"}]},{"f":[{"v":"lamim@10minuteschool.com"},{"v":"Moghbazar Branch"},{"v":"21"},{"v":"372500.0"},{"v":"268000.0"},{"v":"104500.0"}]},{"f":[{"v":"sornali@10minuteschool.com"},{"v":"Panthapath Branch"},{"v":"23"},{"v":"240200.0"},{"v":"196000.0"},{"v":"44200.0"}]},{"f":[{"v":"meem@10minuteschool.com"},{"v":"Panthapath Branch"},{"v":"27"},{"v":"263700.0"},{"v":"223200.0"},{"v":"40500.0"}]}],"jobComplete":true}
], [{"schema":{"fields":[{"name":"ado_email","type":"STRING","mode":"NULLABLE"},{"name":"branch","type":"STRING","mode":"NULLABLE"},{"name":"walkins","type":"INTEGER","mode":"NULLABLE"},{"name":"walkin_admissions","type":"INTEGER","mode":"NULLABLE"},{"name":"free_class_visitors","type":"INTEGER","mode":"NULLABLE"}]},"rows":[{"f":[{"v":"shatabdi@10minuteschool.com"},{"v":"Panthapath Branch"},{"v":"0"},{"v":"0"},{"v":"1"}]},{"f":[{"v":"touhidul.maruf@10minuteschool.com"},{"v":"Uttara Branch"},{"v":"4"},{"v":"0"},{"v":"8"}]},{"f":[{"v":"farjana.eva@10minuteschool.com"},{"v":"Chawkbazar Branch"},{"v":"15"},{"v":"0"},{"v":"24"}]},{"f":[{"v":"farjana@10minuteschool.com"},{"v":"Mirpur Branch"},{"v":"1"},{"v":"1"},{"v":"1"}]},{"f":[{"v":"jogodish@10minuteschool.com"},{"v":"Mirpur Branch"},{"v":"2"},{"v":"1"},{"v":"38"}]},{"f":[{"v":"shatabdi@10minuteschool.com"},{"v":"Mirpur Branch"},{"v":"7"},{"v":"1"},{"v":"42"}]},{"f":[{"v":"rodela@10minuteschool.com"},{"v":"Moghbazar Branch"},{"v":"2"},{"v":"2"},{"v":"2"}]},{"f":[{"v":"puspo@10minuteschool.com"},{"v":"Chawkbazar Branch"},{"v":"23"},{"v":"2"},{"v":"25"}]},{"f":[{"v":"hayatun@10minuteschool.com"},{"v":"Moghbazar Branch"},{"v":"4"},{"v":"3"},{"v":"4"}]},{"f":[{"v":"protyasha@10minuteschool.com"},{"v":"Moghbazar Branch"},{"v":"19"},{"v":"4"},{"v":"9"}]},{"f":[{"v":"raheta@10minuteschool.com"},{"v":"Chawkbazar Branch"},{"v":"23"},{"v":"5"},{"v":"38"}]},{"f":[{"v":"fahim@10minuteschool.com"},{"v":"Mirpur Branch"},{"v":"7"},{"v":"5"},{"v":"40"}]},{"f":[{"v":"eva@10minuteschool.com"},{"v":"Uttara Branch"},{"v":"12"},{"v":"6"},{"v":"8"}]},{"f":[{"v":"meem@10minuteschool.com"},{"v":"Panthapath Branch"},{"v":"16"},{"v":"8"},{"v":"12"}]},{"f":[{"v":"mim@10minuteschool.com"},{"v":"Uttara Branch"},{"v":"11"},{"v":"9"},{"v":"10"}]},{"f":[{"v":"lamim@10minuteschool.com"},{"v":"Moghbazar Branch"},{"v":"10"},{"v":"10"},{"v":"5"}]},{"f":[{"v":"al.amin@10minuteschool.com"},{"v":"Panthapath Branch"},{"v":"16"},{"v":"11"},{"v":"11"}]},{"f":[{"v":"alpana@10minuteschool.com"},{"v":"Uttara Branch"},{"v":"17"},{"v":"12"},{"v":"12"}]},{"f":[{"v":"sornali@10minuteschool.com"},{"v":"Panthapath Branch"},{"v":"26"},{"v":"16"},{"v":"39"}]}],"jobComplete":true}
]','2026-03-31 06:59:31.066653+00'),
('5c09e091-7969-4741-b209-0b8c0d490fca','c53c8480-ce18-4b20-a0bf-96e507c04a65','SELECT branch, programme, COUNT(DISTINCT contact) AS registrations, COUNT(DISTINCT CASE WHEN attendance_status IN (''present'',''present_early'',''present_late'') THEN contact END) AS attendance, ROUND(100 * SAFE_DIVIDE(COUNT(DISTINCT CASE WHEN attendance_status IN (''present'',''present_early'',''present_late'') THEN contact END), COUNT(DISTINCT contact)), 2) AS rta_percentage FROM `tenms-userdb.Marketing_Leads.offline_leads_api` WHERE DATE(formatted_preferred_class_date) = DATE ''2026-03-30'' GROUP BY branch, programme ORDER BY branch, programme LIMIT 1000;
;
','[{"schema":{"fields":[{"name":"branch","type":"STRING","mode":"NULLABLE"},{"name":"programme","type":"STRING","mode":"NULLABLE"},{"name":"registrations","type":"INTEGER","mode":"NULLABLE"},{"name":"attendance","type":"INTEGER","mode":"NULLABLE"},{"name":"rta_percentage","type":"FLOAT","mode":"NULLABLE"}]},"rows":[{"f":[{"v":"Chawkbazar Branch"},{"v":"Kids English (Class 3 - Class 5)"},{"v":"16"},{"v":"1"},{"v":"6.25"}]},{"f":[{"v":"Mirpur Branch"},{"v":"Kids English (KG - Class 2)"},{"v":"83"},{"v":"14"},{"v":"16.87"}]},{"f":[{"v":"Moghbazar Branch"},{"v":"Kids English (KG - Class 2)"},{"v":"46"},{"v":"4"},{"v":"8.7"}]},{"f":[{"v":"Moghbazar Branch"},{"v":"Spoken English Course"},{"v":"66"},{"v":"4"},{"v":"6.06"}]},{"f":[{"v":"Panthapath Branch"},{"v":"Kids English (KG - Class 2)"},{"v":"48"},{"v":"11"},{"v":"22.92"}]},{"f":[{"v":"Uttara Branch"},{"v":"Kids English (Class 3 - Class 5)"},{"v":"22"},{"v":"2"},{"v":"9.09"}]},{"f":[{"v":"Uttara Branch"},{"v":"Kids English (KG - Class 2)"},{"v":"70"},{"v":"0"},{"v":"0.0"}]}],"jobComplete":true}
], [
], [
]','2026-03-31 06:59:36.763649+00'),
('716cad73-9a24-4e58-8125-a14dc608c3ef','6cafcdba-e304-4e84-9f47-7346bda91f02','SELECT COUNT(DISTINCT contact) AS total_attendance FROM `tenms-userdb.Marketing_Leads.offline_leads_api` WHERE attendance_date BETWEEN DATE ''2026-03-01'' AND DATE ''2026-03-30'' AND attendance_status IN (''present'',''present_early'',''present_late'') LIMIT 1000;
;
','[{"schema":{"fields":[{"name":"total_attendance","type":"INTEGER","mode":"NULLABLE"}]},"rows":[{"f":[{"v":"553"}]}],"jobComplete":true}
], [
], [
]','2026-03-31 07:00:08.107881+00')
ON CONFLICT (id) DO NOTHING;