INSERT INTO public.agent_sql_runs (id,message_id,executed_sql,bq_result,created_at) VALUES
('2e70ebdd-5078-466c-8c3d-a4c6a5dd9580','548828bd-91dc-466a-972c-6d5a6c398b7a','SELECT branch, programme, COUNT(DISTINCT contact) AS lead_count FROM `tenms-userdb.Marketing_Leads.offline_leads_api` WHERE submission_date = DATE ''2026-03-30'' GROUP BY branch, programme ORDER BY branch, lead_count DESC LIMIT 1000;
;
','[{"schema":{"fields":[{"name":"branch","type":"STRING","mode":"NULLABLE"},{"name":"programme","type":"STRING","mode":"NULLABLE"},{"name":"lead_count","type":"INTEGER","mode":"NULLABLE"}]},"rows":[{"f":[{"v":"Chawkbazar Branch"},{"v":"Spoken English Junior (Class 6 - Class 10)"},{"v":"32"}]},{"f":[{"v":"Chawkbazar Branch"},{"v":"Spoken English Course"},{"v":"31"}]},{"f":[{"v":"Chawkbazar Branch"},{"v":"IELTS Programme"},{"v":"21"}]},{"f":[{"v":"Chawkbazar Branch"},{"v":"Kids English (KG - Class 2)"},{"v":"14"}]},{"f":[{"v":"Chawkbazar Branch"},{"v":"Kids English (Class 3 - Class 5)"},{"v":"3"}]},{"f":[{"v":"Mirpur Branch"},{"v":"Spoken English Junior (Class 6 - Class 10)"},{"v":"25"}]},{"f":[{"v":"Mirpur Branch"},{"v":"Spoken English Course"},{"v":"23"}]},{"f":[{"v":"Mirpur Branch"},{"v":"Kids English (KG - Class 2)"},{"v":"18"}]},{"f":[{"v":"Mirpur Branch"},{"v":"IELTS Programme"},{"v":"14"}]},{"f":[{"v":"Mirpur Branch"},{"v":"Kids English (Class 3 - Class 5)"},{"v":"3"}]},{"f":[{"v":"Moghbazar Branch"},{"v":"Spoken English Course"},{"v":"13"}]},{"f":[{"v":"Moghbazar Branch"},{"v":"Kids English (KG - Class 2)"},{"v":"11"}]},{"f":[{"v":"Moghbazar Branch"},{"v":"IELTS Programme"},{"v":"4"}]},{"f":[{"v":"Moghbazar Branch"},{"v":"Spoken English Junior (Class 6 - Class 10)"},{"v":"3"}]},{"f":[{"v":"Moghbazar Branch"},{"v":"Kids English (Class 3 - Class 5)"},{"v":"2"}]},{"f":[{"v":"Panthapath Branch"},{"v":"Spoken English Course"},{"v":"19"}]},{"f":[{"v":"Panthapath Branch"},{"v":"IELTS Programme"},{"v":"11"}]},{"f":[{"v":"Panthapath Branch"},{"v":"Spoken English Junior (Class 6 - Class 10)"},{"v":"11"}]},{"f":[{"v":"Panthapath Branch"},{"v":"Kids English (KG - Class 2)"},{"v":"10"}]},{"f":[{"v":"Panthapath Branch"},{"v":"Kids English (Class 3 - Class 5)"},{"v":"1"}]},{"f":[{"v":"Uttara Branch"},{"v":"Spoken English Junior (Class 6 - Class 10)"},{"v":"46"}]},{"f":[{"v":"Uttara Branch"},{"v":"Spoken English Course"},{"v":"41"}]},{"f":[{"v":"Uttara Branch"},{"v":"IELTS Programme"},{"v":"18"}]},{"f":[{"v":"Uttara Branch"},{"v":"Kids English (KG - Class 2)"},{"v":"14"}]},{"f":[{"v":"Uttara Branch"},{"v":"Kids English (Class 3 - Class 5)"},{"v":"8"}]}],"jobComplete":true}
], [
], [
]','2026-03-31 06:58:13.991229+00'),
('9d9a77db-d500-4f7b-9ace-9a8368782fde','de40bf90-059b-4942-b0a5-4baa3b085a13','SELECT programme, COUNT(DISTINCT contact) AS registrations, COUNT(DISTINCT CASE WHEN attendance_status IN (''present'',''present_early'',''present_late'') THEN contact END) AS attendance, COUNT(DISTINCT CASE WHEN admission_date IS NOT NULL THEN contact END) AS admissions, ROUND(SAFE_DIVIDE(COUNT(DISTINCT CASE WHEN attendance_status IN (''present'',''present_early'',''present_late'') THEN contact END), COUNT(DISTINCT contact))*100,2) AS rta_percent, ROUND(SAFE_DIVIDE(COUNT(DISTINCT CASE WHEN admission_date IS NOT NULL THEN contact END), COUNT(DISTINCT CASE WHEN attendance_status IN (''present'',''present_early'',''present_late'') THEN contact END))*100,2) AS ata_percent FROM `tenms-userdb.Marketing_Leads.offline_leads_api` WHERE branch = ''Uttara Branch'' AND submission_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 60 DAY) GROUP BY programme ORDER BY admissions ASC, attendance ASC, registrations DESC LIMIT 1000;
;
','[{"schema":{"fields":[{"name":"programme","type":"STRING","mode":"NULLABLE"},{"name":"registrations","type":"INTEGER","mode":"NULLABLE"},{"name":"attendance","type":"INTEGER","mode":"NULLABLE"},{"name":"admissions","type":"INTEGER","mode":"NULLABLE"},{"name":"rta_percent","type":"FLOAT","mode":"NULLABLE"},{"name":"ata_percent","type":"FLOAT","mode":"NULLABLE"}]},"rows":[{"f":[{"v":"Kids English (Class 3 - Class 5)"},{"v":"139"},{"v":"20"},{"v":"0"},{"v":"14.39"},{"v":"0.0"}]},{"f":[{"v":"Kids English (KG - Class 2)"},{"v":"516"},{"v":"46"},{"v":"0"},{"v":"8.91"},{"v":"0.0"}]},{"f":[{"v":"Spoken English Course"},{"v":"2172"},{"v":"130"},{"v":"9"},{"v":"5.99"},{"v":"6.92"}]},{"f":[{"v":"Spoken English Junior (Class 6 - Class 10)"},{"v":"2827"},{"v":"66"},{"v":"10"},{"v":"2.33"},{"v":"15.15"}]},{"f":[{"v":"IELTS Programme"},{"v":"1275"},{"v":"106"},{"v":"20"},{"v":"8.31"},{"v":"18.87"}]}],"jobComplete":true}
], [
], [
]','2026-03-31 06:30:04.631939+00'),
('82f67db1-ab90-4ed3-adbb-c7a264db40a2','8d239aa0-5a59-4445-8fad-8f37c9b358cf','SELECT * FROM `tenms-userdb.english_centre.ec_ado_fdo_perf_cal` WHERE designation = ''ADO'' ORDER BY Month DESC, Employee_Name ASC LIMIT 1000;
;
','[{"schema":{"fields":[{"name":"Employee_Name","type":"STRING","mode":"NULLABLE"},{"name":"Designation","type":"STRING","mode":"NULLABLE"},{"name":"branch","type":"STRING","mode":"NULLABLE"},{"name":"Month","type":"STRING","mode":"NULLABLE"},{"name":"Working_Days","type":"STRING","mode":"NULLABLE"},{"name":"Present","type":"STRING","mode":"NULLABLE"},{"name":"Absent","type":"STRING","mode":"NULLABLE"},{"name":"Leave","type":"STRING","mode":"NULLABLE"},{"name":"Late","type":"STRING","mode":"NULLABLE"},{"name":"Absent_extra","type":"FLOAT","mode":"NULLABLE"},{"name":"Absent_Total","type":"FLOAT","mode":"NULLABLE"},{"name":"work_days","type":"FLOAT","mode":"NULLABLE"},{"name":"attendance_calculated","type":"FLOAT","mode":"NULLABLE"},{"name":"Movement","type":"STRING","mode":"NULLABLE"},{"name":"Off_Day","type":"STRING","mode":"NULLABLE"},{"name":"Holiday","type":"STRING","mode":"NULLABLE"},{"name":"Single_Punch_Count","type":"STRING","mode":"NULLABLE"},{"name":"attendance_pct","type":"FLOAT","mode":"NULLABLE"},{"name":"team_collaboration_score","type":"FLOAT","mode":"NULLABLE"},{"name":"service_rating_score","type":"FLOAT","mode":"NULLABLE"},{"name":"visitors","type":"INTEGER","mode":"NULLABLE"},{"name":"admissions","type":"INTEGER","mode":"NULLABLE"},{"name":"ado_cvr","type":"FLOAT","mode":"NULLABLE"},{"name":"ado_att_calculation","type":"FLOAT","mode":"NULLABLE"},{"name":"ado_cvr_calculation","type":"FLOAT","mode":"NULLABLE"},{"name":"ado_team_calculation","type":"FLOAT","mode":"NULLABLE"},{"name":"ado_service_calculation","type":"FLOAT","mode":"NULLABLE"},{"name":"fdo_att_calculation","type":"FLOAT","mode":"NULLABLE"},{"name":"fdo_team_calculation","type":"FLOAT","mode":"NULLABLE"},{"name":"fdo_service_calculation","type":"FLOAT","mode":"NULLABLE"},{"name":"employee_score","type":"FLOAT","mode":"NULLABLE"},{"name":"employee_final_score","type":"FLOAT","mode":"NULLABLE"},{"name":"status","type":"STRING","mode":"NULLABLE"}]},"jobComplete":true}
], [
], [
]','2026-03-31 06:34:18.04085+00'),
('5c798c85-11f6-49a9-aeea-a977cfd6569c','33ea3ab8-f5d8-46c0-b1cd-fc83890338e1','SELECT branch, COUNT(DISTINCT contact) AS registrations, COUNT(DISTINCT CASE WHEN attendance_status IN (''present'',''present_early'',''present_late'') THEN contact END) AS attendance, COUNT(DISTINCT CASE WHEN admission_date IS NOT NULL THEN contact END) AS admissions, ROUND(100 * SAFE_DIVIDE(COUNT(DISTINCT CASE WHEN admission_date IS NOT NULL THEN contact END), COUNT(DISTINCT contact)), 2) AS reg_to_admission_pct, ROUND(100 * SAFE_DIVIDE(COUNT(DISTINCT CASE WHEN admission_date IS NOT NULL THEN contact END), COUNT(DISTINCT CASE WHEN attendance_status IN (''present'',''present_early'',''present_late'') THEN contact END)), 2) AS ata_pct FROM `tenms-userdb.Marketing_Leads.offline_leads_api` GROUP BY branch ORDER BY ata_pct DESC, reg_to_admission_pct DESC LIMIT 1000;
;
','[{"schema":{"fields":[{"name":"branch","type":"STRING","mode":"NULLABLE"},{"name":"registrations","type":"INTEGER","mode":"NULLABLE"},{"name":"attendance","type":"INTEGER","mode":"NULLABLE"},{"name":"admissions","type":"INTEGER","mode":"NULLABLE"},{"name":"reg_to_admission_pct","type":"FLOAT","mode":"NULLABLE"},{"name":"ata_pct","type":"FLOAT","mode":"NULLABLE"}]},"rows":[{"f":[{"v":"Uttara Branch"},{"v":"90086"},{"v":"3628"},{"v":"1060"},{"v":"1.18"},{"v":"29.22"}]},{"f":[{"v":"Panthapath Branch"},{"v":"39315"},{"v":"3519"},{"v":"830"},{"v":"2.11"},{"v":"23.59"}]},{"f":[{"v":"Moghbazar Branch"},{"v":"29539"},{"v":"3524"},{"v":"794"},{"v":"2.69"},{"v":"22.53"}]},{"f":[{"v":"Mirpur Branch"},{"v":"67582"},{"v":"5092"},{"v":"831"},{"v":"1.23"},{"v":"16.32"}]},{"f":[{"v":"Chawkbazar Branch"},{"v":"39937"},{"v":"2533"},{"v":"349"},{"v":"0.87"},{"v":"13.78"}]}],"jobComplete":true}
], [
], [
]','2026-03-31 06:35:42.503698+00'),
('e0e851a6-4b17-4ce0-96a6-06d9741a0df7','b4c9f4c1-579e-4322-b08e-2ec85ecd840a','SELECT branch, FORMAT_DATE(''%Y-%m'', submission_date) AS month, COUNT(DISTINCT CASE WHEN attendance_status IN (''present'',''present_early'',''present_late'') THEN contact END) AS attendance, COUNT(DISTINCT CASE WHEN admission_date IS NOT NULL THEN contact END) AS admissions, ROUND(100 * SAFE_DIVIDE(COUNT(DISTINCT CASE WHEN admission_date IS NOT NULL THEN contact END), COUNT(DISTINCT CASE WHEN attendance_status IN (''present'',''present_early'',''present_late'') THEN contact END)), 2) AS ata_percentage FROM `tenms-userdb.Marketing_Leads.offline_leads_api` WHERE submission_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 180 DAY) GROUP BY branch, month ORDER BY month DESC, branch LIMIT 1000;
;
','[{"schema":{"fields":[{"name":"branch","type":"STRING","mode":"NULLABLE"},{"name":"month","type":"STRING","mode":"NULLABLE"},{"name":"attendance","type":"INTEGER","mode":"NULLABLE"},{"name":"admissions","type":"INTEGER","mode":"NULLABLE"},{"name":"ata_percentage","type":"FLOAT","mode":"NULLABLE"}]},"rows":[{"f":[{"v":"Chawkbazar Branch"},{"v":"2026-03"},{"v":"125"},{"v":"3"},{"v":"2.4"}]},{"f":[{"v":"Mirpur Branch"},{"v":"2026-03"},{"v":"146"},{"v":"3"},{"v":"2.05"}]},{"f":[{"v":"Moghbazar Branch"},{"v":"2026-03"},{"v":"93"},{"v":"8"},{"v":"8.6"}]},{"f":[{"v":"Panthapath Branch"},{"v":"2026-03"},{"v":"89"},{"v":"13"},{"v":"14.61"}]},{"f":[{"v":"Uttara Branch"},{"v":"2026-03"},{"v":"63"},{"v":"7"},{"v":"11.11"}]},{"f":[{"v":"Chawkbazar Branch"},{"v":"2026-02"},{"v":"225"},{"v":"19"},{"v":"8.44"}]},{"f":[{"v":"Mirpur Branch"},{"v":"2026-02"},{"v":"353"},{"v":"12"},{"v":"3.4"}]},{"f":[{"v":"Moghbazar Branch"},{"v":"2026-02"},{"v":"173"},{"v":"15"},{"v":"8.67"}]},{"f":[{"v":"Panthapath Branch"},{"v":"2026-02"},{"v":"233"},{"v":"19"},{"v":"8.15"}]},{"f":[{"v":"Uttara Branch"},{"v":"2026-02"},{"v":"257"},{"v":"27"},{"v":"10.51"}]},{"f":[{"v":"Chawkbazar Branch"},{"v":"2026-01"},{"v":"558"},{"v":"49"},{"v":"8.78"}]},{"f":[{"v":"Mirpur Branch"},{"v":"2026-01"},{"v":"844"},{"v":"56"},{"v":"6.64"}]},{"f":[{"v":"Moghbazar Branch"},{"v":"2026-01"},{"v":"521"},{"v":"52"},{"v":"9.98"}]},{"f":[{"v":"Panthapath Branch"},{"v":"2026-01"},{"v":"610"},{"v":"42"},{"v":"6.89"}]},{"f":[{"v":"Uttara Branch"},{"v":"2026-01"},{"v":"569"},{"v":"41"},{"v":"7.21"}]},{"f":[{"v":"Chawkbazar Branch"},{"v":"2025-12"},{"v":"206"},{"v":"43"},{"v":"20.87"}]},{"f":[{"v":"Mirpur Branch"},{"v":"2025-12"},{"v":"259"},{"v":"44"},{"v":"16.99"}]},{"f":[{"v":"Moghbazar Branch"},{"v":"2025-12"},{"v":"188"},{"v":"56"},{"v":"29.79"}]},{"f":[{"v":"Panthapath Branch"},{"v":"2025-12"},{"v":"158"},{"v":"25"},{"v":"15.82"}]},{"f":[{"v":"Uttara Branch"},{"v":"2025-12"},{"v":"130"},{"v":"39"},{"v":"30.0"}]},{"f":[{"v":"Chawkbazar Branch"},{"v":"2025-11"},{"v":"101"},{"v":"20"},{"v":"19.8"}]},{"f":[{"v":"Mirpur Branch"},{"v":"2025-11"},{"v":"125"},{"v":"19"},{"v":"15.2"}]},{"f":[{"v":"Moghbazar Branch"},{"v":"2025-11"},{"v":"57"},{"v":"20"},{"v":"35.09"}]},{"f":[{"v":"Panthapath Branch"},{"v":"2025-11"},{"v":"62"},{"v":"19"},{"v":"30.65"}]},{"f":[{"v":"Uttara Branch"},{"v":"2025-11"},{"v":"54"},{"v":"25"},{"v":"46.3"}]},{"f":[{"v":"Chawkbazar Branch"},{"v":"2025-10"},{"v":"85"},{"v":"10"},{"v":"11.76"}]},{"f":[{"v":"Mirpur Branch"},{"v":"2025-10"},{"v":"205"},{"v":"34"},{"v":"16.59"}]},{"f":[{"v":"Moghbazar Branch"},{"v":"2025-10"},{"v":"123"},{"v":"40"},{"v":"32.52"}]},{"f":[{"v":"Panthapath Branch"},{"v":"2025-10"},{"v":"109"},{"v":"40"},{"v":"36.7"}]},{"f":[{"v":"Uttara Branch"},{"v":"2025-10"},{"v":"163"},{"v":"26"},{"v":"15.95"}]}],"jobComplete":true}
], [
], [
]','2026-03-31 06:53:32.993241+00')
ON CONFLICT (id) DO NOTHING;