
CREATE TABLE public.suggested_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  message text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.suggested_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone authenticated can read suggestions"
ON public.suggested_messages
FOR SELECT
TO authenticated
USING (true);

INSERT INTO public.suggested_messages (message) VALUES
('Show today''s registrations by branch'),
('Show today''s attendance by branch'),
('Show today''s admissions by branch'),
('What is today''s RTA by branch?'),
('What is today''s ATA by branch?'),
('Show yesterday''s registrations by branch'),
('Show yesterday''s attendance by branch'),
('Show yesterday''s admissions by branch'),
('Compare today vs yesterday registrations'),
('Compare today vs yesterday attendance'),
('Compare today vs yesterday admissions'),
('Show this week''s registrations by branch'),
('Show this week''s attendance by branch'),
('Show this week''s admissions by branch'),
('Show this month''s registrations by branch'),
('Show this month''s attendance by branch'),
('Show this month''s admissions by branch'),
('Show branch-wise walk-ins today'),
('Show branch-wise walk-ins this week'),
('Show branch-wise walk-ins this month'),
('Show walk-in admissions this month'),
('Show lead source wise registrations'),
('Show data source wise registrations'),
('Which branch has highest attendance?'),
('Which branch has highest admissions?'),
('Which programme has highest admissions?'),
('Which branch has best RTA?'),
('Which branch has best ATA?'),
('Which programme has best ATA?'),
('Show RTA trend for last 7 days'),
('Show ATA trend for last 7 days'),
('Show ADO wise admissions today'),
('Show ADO wise admissions this week'),
('Show ADO wise admissions this month'),
('Show ADO wise revenue this month'),
('Show ADO wise due collected'),
('Show ADO wise due amount'),
('Top 5 ADOs by admissions'),
('Top 5 ADOs by revenue'),
('Top 5 ADOs by collection'),
('Show BM wise branch perform'),
('Show Uttara branch performance today'),
('Show Panthapath branch performance today'),
('Show Mirpur branch performance today'),
('Show Moghbazar branch performance today'),
('Show Chawkbazar branch performance today'),
('Show IELTS registrations this month'),
('Show IELTS attendance this month'),
('Show IELTS admissions this month'),
('Show today''s free class visitors by branch'),
('Show this week''s free class visitors by branch'),
('Show this month''s free class visitors by branch'),
('Show unregistered free class visitors today'),
('Show registered free class visitors today'),
('Show today''s tele-eligible leads'),
('Show this week''s tele-eligible leads'),
('Show today''s called vs uncalled leads'),
('Show this week''s called vs uncalled leads'),
('Show calling status summary for today'),
('Show confirmed vs pitched vs reached this week'),
('Show undialled leads for today'),
('Show undialled leads for tomorrow''s classes'),
('Which cohort has the most undialled leads today?'),
('Which cohort has the most absent users this week?'),
('Show admissions by Al Amin this month'),
('Show admissions by Sornali Ahmed this month'),
('Show admissions by Jogodish Ghosh this month'),
('Show admissions by Humayra Kabir Shatabdi this month'),
('Show admissions by Marajul Haque Fahim this month'),
('Show admissions by Nomit Akone Lamim this month'),
('Show this month''s booking revenue'),
('Show this month''s due amount by branch'),
('Show this month''s collection by payment method'),
('Which source gives the best ATA?'),
('Which source gives the worst RTA?'),
('Are Facebook leads attending well?'),
('Are Booking System leads converting well?'),
('Is ClassroomOS contributing more now?'),
('How much are walk-ins helping revenue?'),
('Which branch has the best RTA trend?'),
('Which branch has the best ATA trend?'),
('Show branches ranked by growth'),
('Show programmes ranked by growth'),
('Which branch improved most this week?'),
('Which branch dropped most this week?'),
('Which lead source brings best admissions?'),
('Which lead source brings weak attendance?'),
('Show weekend vs weekday performance'),
('Show morning vs afternoon slot trends'),
('Summarize this week in simple words'),
('Show BM-level branch performance'),
('Show FDO impact on visitor handling'),
('Show IELTS health this month'),
('Show Spoken English Course health'),
('Show SE Junior health this month'),
('Show Kids English health this month'),
('Are Kids programmes growing?'),
('Is IELTS slowing down anywhere?'),
('Which programme needs marketing push?'),
('Which programme needs ops attention?'),
('Give me 3 actions for today'),
('What should Rubab focus on today?'),
('What should Rezu focus on today?');
