ALTER TABLE public.chat_sessions
  ADD COLUMN mode TEXT NOT NULL DEFAULT 'ec';

ALTER TABLE public.chat_messages
  ADD COLUMN mode TEXT NOT NULL DEFAULT 'ec';

ALTER TABLE public.suggested_messages
  ADD COLUMN mode TEXT NOT NULL DEFAULT 'ec';

-- Ensure existing suggested messages are associated with the EC mode by default.
UPDATE public.suggested_messages
SET mode = 'ec'
WHERE mode IS NULL;

-- Add 10MS-specific suggested messages.
INSERT INTO public.suggested_messages (message, mode) VALUES
('Show online segment registrations for the 10MS mobile app'),
('Compare OB vs HSC revenue this month'),
('What is the conversion rate for TenTen product signups?'),
('Show traffic and registration sources for SSC campaigns'),
('Show paid vs organic lead performance for online courses'),
('Show week-over-week active learner trends for OB'),
('Which online product had the best retention this month?'),
('Show revenue by product category for the last 30 days'),
('Show top-performing ads driving 10MS registrations'),
('Compare current funnel performance between OB and SSC'),
('Show engagement rates for TenTen learners this week'),
('Show daily active users for online segments'),
('Which campaign had the highest ROAS last month?'),
('Show refund and churn signal for 10MS products'),
('Summarize online course performance for the past week'),
('Show FY26 recognized revenue by product tier'),
('Compare OB 26 vs OB 27 booking momentum'),
('Show HSC 26, 27, and 28 revenue contribution this month'),
('Show SSC 26 vs SSC 27 registrations this season'),
('Which product tier is closest to EBITDA breakeven?'),
('Show monthly recognized revenue for OB in FY26'),
('Show monthly recognized revenue for HSC in FY26'),
('Show monthly recognized revenue for SSC in FY26'),
('Compare Dec and Jan booking season performance YoY'),
('Show enrollment season bookings for FY26'),
('Show recognized revenue vs bookings for the online segment'),
('Which products are contributing most to FY26 revenue?'),
('Show publications revenue trend in FY26'),
('How much revenue came from publications in the last 7 months?'),
('Show Masterbook attachment rate by product'),
('Show TenTen usage among paid learners'),
('Show SuperPrep adoption by cohort'),
('Compare OB pricing bands for class 6 to 8 vs class 9 to 10'),
('Show average selling price by product tier'),
('Show revenue per learner by product'),
('Which product has the highest revenue per enrollment?'),
('Show HSC C1 to C2 renewal rate trend'),
('Why is HSC renewal only 18 percent?'),
('Show renewal rate by HSC cohort'),
('Compare renewal performance across HSC 26, 27, and 28'),
('Which HSC cohort has the weakest renewal signal?'),
('Show churn signal for HSC learners'),
('Show retention by product tier'),
('Which online product has the best retention?'),
('Show repeat purchase behavior across online products'),
('Show learner retention after the first 3 months'),
('Show telesales share of total enrollments'),
('How much of acquisition is guided vs self-serve?'),
('Show MPB channel contribution this month'),
('Show platform self-serve enrollments this month'),
('Show referral contribution to enrollments'),
('Show free demo class contribution to enrollments'),
('Show KS event contribution to enrollments'),
('Which acquisition channel has the best conversion rate?'),
('Which acquisition channel has the worst conversion rate?'),
('Show paid vs organic conversion by product'),
('Show traffic to registration funnel for OB'),
('Show registration to payment funnel for HSC'),
('Show payment conversion by acquisition channel'),
('What is the likely CAC issue in the demo class channel?'),
('Show unattributed demo class enrollments'),
('Estimate demo class CAC gap using available data'),
('Show ROAS by campaign for SSC'),
('Show ROAS by campaign for HSC'),
('Which campaigns are driving the best quality learners?'),
('Show traffic quality by source for OB'),
('Show app vs web conversion for online products'),
('Show WhatsApp or Banglalink channel performance'),
('Show TenTen as an acquisition funnel for OB'),
('Is freemium TenTen viable as an OB acquisition funnel?'),
('Show paid user conversion after TenTen engagement'),
('Show TenTen engagement vs renewal correlation'),
('Show Delivery-related revenue contribution'),
('Show traffic trend for the online segment this month'),
('Show active learner trend by product'),
('Show DAU trend for TenTen this month'),
('Show cohort health for OB 26'),
('Show cohort health for SSC 27'),
('Show cohort health for HSC 28'),
('Which cohort is underperforming against expectation?'),
('Show product mix shift over FY26'),
('Show contribution margin by product if available'),
('Which product is dragging margin the most?'),
('Show telesales efficiency by team or agent'),
('Show guided sales dependency by product'),
('Which product depends most on telesales?'),
('Show self-serve growth trend over time'),
('Show guardian phone capture gap in enrollment flow'),
('How many enrollments are missing guardian phone numbers?'),
('Show unresolved operational blockers in the online funnel'),
('What should the online segment team focus on this week?'),
('Summarize the biggest risks in the online academic segment'),
('Summarize the biggest growth opportunities in the online academic segment'),
('Show ADM 26 launch readiness signals'),
('What should be monitored before ADM 26 launch?'),
('Show bundled product performance for Masterbook, TenTen, and SuperPrep'),
('Which bundled product is contributing most to learner value?'),
('Show online segment performance in one executive summary');
